import type { Program } from "./types/program.types";

export const programStaticData: Program[] = [
  {
    id: 1,
    name: "Computer Science",
    university: "Warsaw University of Technology",
    city: "Warsaw",
    level: "Bachelor",
    duration: "3.5 years",
    language: "English",
    tuition: 4000,
    rating: 4.8,
    studentsCount: 1250,
    nextDeadline: "2025-04-15",
    tags: [
      "AI & Machine Learning",
      "Software Engineering",
      "Data Science",
    ],
  },
  {
    id: 2,
    name: "International Business",
    university: "Kraków University of Economics",
    city: "Kraków",
    level: "Master",
    duration: "2 years",
    language: "English",
    tuition: 3500,
    rating: 4.6,
    studentsCount: 890,
    nextDeadline: "2025-03-20",
    tags: ["Global Markets", "Digital Marketing", "Entrepreneurship"],
  },
  {
    id: 3,
    name: "Biomedical Engineering",
    university: "Wrocław University of Science",
    city: "Wrocław",
    level: "Bachelor",
    duration: "3.5 years",
    language: "English",
    tuition: 4500,
    rating: 4.7,
    studentsCount: 420,
    nextDeadline: "2025-05-01",
    tags: ["Medical Devices", "Biotechnology", "Research Focus"],
  },
  {
      id: 4,
      name: "Sustainable Architecture",
      university: "Gdańsk University of Technology",
      city: "Gdańsk",
      level: "Master",
      duration: "2.5 years",
      language: "English",
      tuition: 4500,
      rating: 4.6,
      studentsCount: 380,
      nextDeadline: "2025-04-30",
      tags: ["Eco-friendly Design", "Urban Planning", "Smart Buildings"],
    },
];


